// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttributeFormController from "./attribute_form_controller"
application.register("attribute-form", AttributeFormController)

import AttributeReorderController from "./attribute_reorder_controller"
application.register("attribute-reorder", AttributeReorderController)

import BulkActionsController from "./bulk_actions_controller"
application.register("bulk-actions", BulkActionsController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GlobalSearchController from "./global_search_controller"
application.register("global-search", GlobalSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import InlineEditorController from "./inline_editor_controller"
application.register("inline-editor", InlineEditorController)

import LabelSelectorController from "./label_selector_controller"
application.register("label-selector", LabelSelectorController)

import LabelTreeController from "./label_tree_controller"
application.register("label-tree", LabelTreeController)

import LayoutController from "./layout_controller"
application.register("layout", LayoutController)

import MobileSidebarController from "./mobile_sidebar_controller"
application.register("mobile-sidebar", MobileSidebarController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OptionsManagerController from "./options_manager_controller"
application.register("options-manager", OptionsManagerController)

import ProductFormController from "./product_form_controller"
application.register("product-form", ProductFormController)

import ProductLabelsController from "./product_labels_controller"
application.register("product-labels", ProductLabelsController)
