FactoryBot.define do
  factory :label do
    company
    sequence(:code) { |n| "label#{n}" }
    sequence(:name) { |n| "Label #{n}" }
    label_type { "category" }
    full_code { nil } # Auto-generated by callback
    full_name { nil } # Auto-generated by callback
    description { nil }
    info { {} }
    parent_label_id { nil }
    label_positions { nil }
    product_default_restriction { nil }

    # Trait for root label
    trait :root do
      parent_label_id { nil }
      code { "root" }
      name { "Root Category" }
    end

    # Trait for child label
    trait :child do
      association :parent_label, factory: :label
      code { "child" }
      name { "Child Category" }
    end

    # Trait with restriction - allow
    trait :allow_products do
      product_default_restriction { :allow }
    end

    # Trait with restriction - deny
    trait :deny_products do
      product_default_restriction { :deny }
    end

    # Trait with position
    trait :positioned do
      sequence(:label_positions) { |n| n }
    end

    # Trait with description
    trait :with_description do
      description { "This is a detailed description of the label category" }
    end

    # Trait with localized info
    trait :with_localized_info do
      info do
        {
          'localized_value' => {
            'en' => name,
            'de' => "#{name} (DE)",
            'fr' => "#{name} (FR)"
          }
        }
      end
    end

    # Trait for different label types
    trait :category_type do
      label_type { "category" }
    end

    trait :tag_type do
      label_type { "tag" }
    end

    trait :brand_type do
      label_type { "brand" }
    end

    # Trait with sublabels (children)
    trait :with_sublabels do
      transient do
        sublabels_count { 3 }
      end

      after(:create) do |label, evaluator|
        create_list(:label, evaluator.sublabels_count, parent_label: label, company: label.company)
      end
    end

    # Trait with products
    trait :with_products do
      transient do
        products_count { 5 }
      end

      after(:create) do |label, evaluator|
        evaluator.products_count.times do
          product = create(:product)
          create(:product_label, label: label, product: product)
        end
      end
    end

    # Trait for deep hierarchy (3 levels)
    trait :with_deep_hierarchy do
      after(:create) do |label|
        child = create(:label, parent_label: label, code: "level2", name: "Level 2", company: label.company)
        create(:label, parent_label: child, code: "level3", name: "Level 3", company: label.company)
      end
    end
  end
end
