require 'rails_helper'

RSpec.describe VariantAttributeInheritance, type: :service do
  let(:company) { create(:company) }
  let(:parent) { create(:product, :configurable_variant, company: company) }
  let(:variant) { create(:product, :sellable, company: company) }
  # Seeded with every company; flagged subproduct_mandatory by SystemAttributes
  let(:weight) { company.product_attributes.find_by!(code: 'weight') }
  let(:name_attr) { create(:product_attribute, company: company, code: 'subtitle', subproduct_mandatory: false) }

  def value_of(product, attribute)
    product.product_attribute_values.find_by(product_attribute: attribute)
  end

  def call
    described_class.new(superproduct: parent, subproduct: variant).call
  end

  it 'copies the value and info of a flagged attribute' do
    create(:product_attribute_value, product: parent, product_attribute: weight, value: '30', info: { 'unit' => 'g' })

    call

    copied = value_of(variant, weight)
    expect(copied.value).to eq('30')
    expect(copied.info).to eq({ 'unit' => 'g' })
  end

  it 'skips attributes that are not flagged' do
    create(:product_attribute_value, product: parent, product_attribute: name_attr, value: 'Hello')

    call

    expect(value_of(variant, name_attr)).to be_nil
  end

  it "copies the attribute's default when the parent has no value" do
    weight.update!(default_value: '5')

    call

    expect(value_of(variant, weight).value).to eq('5')
  end

  it 'skips the attribute when parent value and default are both blank' do
    expect(call).to eq(0)
    expect(value_of(variant, weight)).to be_nil
  end

  it 'keeps a value the variant already has' do
    create(:product_attribute_value, product: parent, product_attribute: weight, value: '30')
    create(:product_attribute_value, product: variant, product_attribute: weight, value: '45')

    expect(call).to eq(0)
    expect(value_of(variant, weight).value).to eq('45')
  end

  it 'returns the number of values created' do
    purchase_price = company.product_attributes.find_by!(code: 'purchase_price')
    create(:product_attribute_value, product: parent, product_attribute: weight, value: '30')
    create(:product_attribute_value, product: parent, product_attribute: purchase_price, value: '2000')

    expect(call).to eq(2)
  end

  describe 'when a variant is linked' do
    before { create(:product_attribute_value, product: parent, product_attribute: weight, value: '30') }

    it 'copies values into a variant of a configurable product' do
      create(:product_configuration, superproduct: parent, subproduct: variant)

      expect(value_of(variant, weight).value).to eq('30')
    end

    it 'leaves a bundle component untouched' do
      bundle = create(:product, :bundle, company: company)
      create(:product_attribute_value, product: bundle, product_attribute: weight, value: '99')

      create(:product_configuration, superproduct: bundle, subproduct: variant)

      expect(value_of(variant, weight)).to be_nil
    end

    it 'gives variants generated by VariantGeneratorService the parent value' do
      create(:configuration, :size, product: parent)

      VariantGeneratorService.new(parent).generate!

      variants = parent.reload.subproducts
      expect(variants).not_to be_empty
      expect(variants.map { |v| value_of(v, weight)&.value }.uniq).to eq([ '30' ])
    end
  end
end
